[package]
name = "video_watch_upload_azure"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45", features = ["full"] }
reqwest = { version = "0.12" }
indexmap = "2.9"
crc32fast = "1.4"
